theme = "theme"

[editor]
mouse = false
middle-click-paste = false
line-number = "relative"
cursorline = true
bufferline = "always"
completion-timeout = 20
completion-trigger-len = 1
color-modes = true
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "diagnostics"]
center = ["file-name", "read-only-indicator"]
right = ["register", "selections", "position", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["spacer", "diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.gutters.line-numbers]
min-width = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
X = "extend_line_above"
C-n = ":new"
A-S-f = ":format"
