[general]
import = ["default-bindings.toml", "bindings.toml"]

[window]
padding = { x = 16 }
decorations = "None"

[scrolling]
multiplier = 4

[font]
size = 14

[cursor]
unfocused_hollow = false

[terminal]
shell = "elvish"
